In [18]:
import tensorflow as tf
import numpy as np
import distanceTF as dt
import coordinate as cr
import BetaMatrix as bt

In [64]:
coordinate = cr.geodata(3)#Generate the coordinate
a = dt.Distance(coordinate)#distance matrix
BetaMatrix=bt.tfBetaMatrix(a, [0.3,0.1],bt.exponentialKernel)
b=bt.tfBetaRunning(BetaMatrix)#BetaMatrix for testing
print(b)


[[ 0.3         0.05930516  0.01293884]
 [ 0.05930516  0.3         0.00266249]
 [ 0.01293884  0.00266249  0.3       ]]


In [65]:
#3 people in testing
state=np.array([1,1,0])
tfState=tf.constant(state)

In [66]:
c=tf.equal(tfState,1)
d=tf.where(c)
init=tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init)
    indexOf1=sess.run(d)
    print(indexOf1)

[[0]
 [1]]


In [67]:
cc=tf.equal(tfState,0)
dd=tf.where(cc)
init=tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init)
    indexOf0=sess.run(dd)
    print(indexOf0)

[[2]]


The index of infected people is [[0]], and the index of susceptible people is [[1][2]],
Then we interested in column 0 with rows 1,2
or vice versa, the columns 1,2 with row 0. Because the BetaMatrix is symmetric.
We want the sum of the column which state is 1 to assign it into the row of state is 0
The numpy version is probInfect[state==0] = BetaMatrix[:, state==1].sum(1)[state==0]
But due to the limit of boolean index of tensorflow are not available yet, so we have to use the tf.equal,tf.where, tf.indice and tf.scatter_update. 


In [70]:
#row = tf.gather(b, indexOf0)
row=tf.gather_nd(b,indexOf0)
#rowCol=tf.gather_nd(row,indexOf1)
roadhug=tf.convert_to_tensor(b[indexOf0,indexOf1])
sumrum=tf.reduce_sum(roadhug,0)
tf.Session().run(roadhug)  
#tf.Session().run(sumrum)

array([[ 0.01293884],
       [ 0.00266249]])

There are some problem in the reduce_sum.

What we want is just sum up the infected individuals column 

In [61]:
import TansformProbability as tp

In [62]:
tp.tfTransformOneColumn(np.array([1,0,0]),b,0.3)

ValueError: Shapes (1,) and (?, 1, 1) are not compatible