In [52]:
import tensorflow as tf
import numpy as np

In [53]:
a=tf.constant([1,0,0,0,1,0,0])
b=tf.constant([5,4,3,3,2,1,8])
c=tf.equal(a,1)
d=tf.where(c)
init=tf.initialize_all_variables()

In [54]:
with tf.Session() as sess:
    sess.run(init)
    indexOf1=sess.run(d)
    print(indexOf1)

[[0]
 [4]]


In [55]:
indexOf1.shape
Updates=5*np.ones(indexOf1.shape)
print(Updates)

[[ 5.]
 [ 5.]]


In [56]:
data=tf.Variable([1,2,3,4,5])
sca=tf.scatter_update(data,indexOf1,Updates)
init=tf.initialize_all_variables()

In [57]:
with tf.Session() as sess:
    sess.run(init)
    UpdateResult=sess.run(sca)
    print(UpdateResult)

[5 2 3 4 5]


In [58]:
tf.reduce_sum?